import { Platform, StyleSheet } from 'react-native'
import { colors } from './theme'

export const networkColors = {
  ...colors,
  blue: '#60A5FA',
  cyan: '#38BDF8',
  orange: '#FBBF24',
  purple: '#C4B5FD',
} as const

const monoFont = Platform.select({ ios: 'Menlo', android: 'monospace' })

export const networkStyles = StyleSheet.create({
  fill: { flex: 1 },
  listContent: { gap: 8, padding: 16, paddingBottom: 36 },
  toolbar: { gap: 10 },
  metrics: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderColor: colors.borderMuted,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 70,
    paddingHorizontal: 8,
  },
  metric: { alignItems: 'center', flex: 1, gap: 3 },
  metricValue: {
    color: colors.text,
    fontFamily: monoFont,
    fontSize: 15,
    fontWeight: '700',
  },
  metricValueError: { color: colors.danger },
  metricLabel: { color: colors.muted, fontSize: 10, fontWeight: '600' },
  capture: { alignItems: 'center', flex: 1, gap: 1 },
  actionRow: { flexDirection: 'row', gap: 8 },
  sortControl: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderColor: colors.borderMuted,
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-end',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  sortLabel: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  actionButton: {
    alignItems: 'center',
    backgroundColor: colors.raised,
    borderColor: colors.borderMuted,
    borderRadius: 7,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
  },
  actionButtonText: { color: colors.secondary, fontSize: 12, fontWeight: '700' },
  destructiveText: { color: colors.danger },
  searchInput: {
    backgroundColor: colors.background,
    borderColor: colors.borderMuted,
    borderRadius: 7,
    borderWidth: 1,
    color: colors.text,
    fontSize: 14,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  filterScroll: { flexGrow: 0 },
  filterContent: {
    backgroundColor: colors.background,
    borderRadius: 7,
    flexDirection: 'row',
    gap: 2,
    padding: 3,
  },
  filterButton: {
    alignItems: 'center',
    borderRadius: 5,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  filterButtonActive: { backgroundColor: colors.raisedActive },
  filterText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  filterTextActive: { color: colors.text },
  showing: { color: colors.muted, fontFamily: monoFont, fontSize: 10 },
  requestRow: {
    backgroundColor: colors.raised,
    borderColor: colors.borderMuted,
    borderRadius: 8,
    borderWidth: 1,
    gap: 7,
    minHeight: 82,
    padding: 12,
  },
  requestTopLine: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  methodBadge: {
    alignItems: 'center',
    borderRadius: 5,
    justifyContent: 'center',
    minHeight: 22,
    minWidth: 48,
    paddingHorizontal: 7,
  },
  methodGet: { backgroundColor: '#1D4ED8' },
  methodPost: { backgroundColor: '#6D28D9' },
  methodMutation: { backgroundColor: '#B45309' },
  methodDelete: { backgroundColor: '#B91C1C' },
  methodOther: { backgroundColor: '#475569' },
  methodText: {
    color: '#FFFFFF',
    fontFamily: monoFont,
    fontSize: 10,
    fontWeight: '800',
  },
  status: { fontFamily: monoFont, fontSize: 12, fontWeight: '700' },
  statusSuccess: { color: colors.accent },
  statusRedirect: { color: networkColors.cyan },
  statusWarning: { color: networkColors.orange },
  statusError: { color: colors.danger },
  host: { color: colors.muted, flex: 1, fontSize: 11, textAlign: 'right' },
  path: {
    color: colors.text,
    fontFamily: monoFont,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  metadata: { color: colors.muted, fontFamily: monoFont, fontSize: 10 },
  empty: { alignItems: 'center', gap: 6, paddingHorizontal: 24, paddingVertical: 48 },
  emptyTitle: { color: colors.secondary, fontSize: 15, fontWeight: '700' },
  emptyBody: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  errorText: { color: colors.danger, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  detailHeader: {
    alignItems: 'center',
    borderBottomColor: colors.borderMuted,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 52,
    paddingHorizontal: 16,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.raised,
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  backText: { color: colors.secondary, fontSize: 20, fontWeight: '700' },
  detailHeaderTitle: { color: colors.text, flex: 1, fontSize: 16, fontWeight: '700' },
  detailContent: { gap: 10, padding: 16, paddingBottom: 36 },
  summary: {
    backgroundColor: colors.background,
    borderColor: colors.borderMuted,
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  summaryTop: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  summaryUrl: { color: colors.secondary, fontFamily: monoFont, fontSize: 11, lineHeight: 17 },
  segmented: {
    backgroundColor: colors.background,
    borderRadius: 7,
    flexDirection: 'row',
    padding: 3,
  },
  segment: { alignItems: 'center', borderRadius: 5, flex: 1, justifyContent: 'center', minHeight: 40 },
  segmentActive: { backgroundColor: colors.raisedActive },
  segmentText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  segmentTextActive: { color: colors.text },
  section: {
    backgroundColor: colors.background,
    borderColor: colors.borderMuted,
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  sectionTitle: { color: colors.text, flex: 1, fontSize: 12, fontWeight: '700' },
  sectionIndicator: { color: colors.muted, fontFamily: monoFont, fontSize: 16 },
  rows: { borderTopColor: colors.borderMuted, borderTopWidth: 1, paddingHorizontal: 12 },
  keyValueRow: { borderBottomColor: colors.borderMuted, borderBottomWidth: 1, gap: 4, paddingVertical: 9 },
  keyText: { color: networkColors.blue, fontFamily: monoFont, fontSize: 10, fontWeight: '700' },
  valueText: { color: colors.secondary, fontFamily: monoFont, fontSize: 11, lineHeight: 17 },
  bodyToolbar: {
    alignItems: 'center',
    borderTopColor: colors.borderMuted,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 8,
  },
  copyButton: {
    alignItems: 'center',
    backgroundColor: colors.raised,
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 11,
  },
  copyButtonText: { color: colors.accent, fontSize: 11, fontWeight: '700' },
  bodyText: {
    backgroundColor: colors.raised,
    color: colors.secondary,
    fontFamily: monoFont,
    fontSize: 11,
    lineHeight: 17,
    margin: 10,
    padding: 10,
  },
})
