import { Platform, StyleSheet } from 'react-native'

export const colors = {
  backdrop: 'rgba(2, 6, 23, 0.76)',
  background: '#0F172A',
  surface: '#111827',
  raised: '#1E293B',
  raisedActive: '#263449',
  border: '#475569',
  borderMuted: 'rgba(148, 163, 184, 0.24)',
  text: '#F8FAFC',
  secondary: '#CBD5E1',
  muted: '#94A3B8',
  accent: '#22C55E',
  accentSurface: '#123222',
  danger: '#FCA5A5',
  dangerBorder: 'rgba(248, 113, 113, 0.42)',
} as const

const monoFont = Platform.select({ ios: 'Menlo', android: 'monospace' })

export const styles = StyleSheet.create({
  backdrop: {
    backgroundColor: colors.backdrop,
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.surface,
    borderColor: colors.borderMuted,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    maxHeight: '94%',
    minHeight: '72%',
    overflow: 'hidden',
  },
  screenBackdrop: { backgroundColor: colors.surface, flex: 1 },
  screen: { backgroundColor: colors.surface, flex: 1, overflow: 'hidden' },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 12,
    paddingHorizontal: 18,
    paddingTop: 16,
  },
  headerCopy: { flex: 1, paddingRight: 12 },
  eyebrow: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  title: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '700',
    marginTop: 3,
  },
  closeButton: {
    alignItems: 'center',
    backgroundColor: colors.raised,
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  closeText: { color: colors.secondary, fontSize: 25, lineHeight: 27 },
  tabBar: {
    backgroundColor: colors.background,
    borderRadius: 10,
    flexDirection: 'row',
    marginBottom: 4,
    marginHorizontal: 16,
    padding: 4,
  },
  tab: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 10,
  },
  tabActive: { backgroundColor: colors.raisedActive },
  tabText: { color: colors.muted, fontSize: 13, fontWeight: '600' },
  tabTextActive: { color: colors.text },
  content: { gap: 10, padding: 16, paddingBottom: 36 },
  infoCard: {
    backgroundColor: colors.accentSurface,
    borderColor: 'rgba(34, 197, 94, 0.34)',
    borderRadius: 12,
    borderWidth: 1,
    padding: 13,
  },
  infoTitle: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 5,
  },
  infoText: { color: colors.secondary, fontSize: 12, lineHeight: 18 },
  searchInput: {
    backgroundColor: colors.background,
    borderColor: colors.borderMuted,
    borderRadius: 10,
    borderWidth: 1,
    color: colors.text,
    fontSize: 14,
    minHeight: 44,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  entryCard: {
    backgroundColor: colors.raised,
    borderColor: colors.borderMuted,
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 74,
    padding: 13,
  },
  entryCardSelected: {
    backgroundColor: colors.raisedActive,
    borderColor: colors.accent,
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  entryLabel: { color: colors.text, flex: 1, fontSize: 15, fontWeight: '700' },
  entryKind: {
    color: colors.accent,
    fontFamily: monoFont,
    fontSize: 10,
    marginLeft: 8,
    textTransform: 'uppercase',
  },
  entryKey: {
    color: colors.muted,
    fontFamily: monoFont,
    fontSize: 11,
    marginTop: 4,
  },
  preview: {
    color: colors.secondary,
    fontFamily: monoFont,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 8,
  },
  emptyState: { alignItems: 'center', paddingHorizontal: 18, paddingVertical: 28 },
  emptyTitle: { color: colors.secondary, fontSize: 15, fontWeight: '600' },
  emptyText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    textAlign: 'center',
  },
  detailCard: {
    backgroundColor: colors.background,
    borderColor: colors.borderMuted,
    borderRadius: 14,
    borderWidth: 1,
    padding: 13,
  },
  detailHeading: { flex: 1, paddingRight: 10 },
  sectionTitle: { color: colors.text, fontSize: 17, fontWeight: '700' },
  detailKey: {
    color: colors.muted,
    fontFamily: monoFont,
    fontSize: 10,
    marginTop: 3,
  },
  smallButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  smallButtonText: { color: colors.accent, fontSize: 12, fontWeight: '700' },
  detailDescription: {
    color: colors.secondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 11,
  },
  fieldRow: {
    alignItems: 'center',
    borderBottomColor: colors.borderMuted,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 8,
  },
  fieldEditButton: { flex: 1, justifyContent: 'center', minHeight: 44 },
  fieldName: { color: colors.text, fontFamily: monoFont, fontSize: 12, fontWeight: '600' },
  fieldValue: {
    color: colors.secondary,
    fontFamily: monoFont,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 3,
  },
  removeButton: {
    alignItems: 'center',
    borderColor: colors.dangerBorder,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 10,
  },
  removeText: { color: colors.danger, fontSize: 11, fontWeight: '700' },
  editorBlock: { gap: 7, paddingTop: 14 },
  editorTitle: { color: colors.secondary, fontSize: 13, fontWeight: '700' },
  inputLabel: { color: colors.muted, fontSize: 11, fontWeight: '600', marginTop: 3 },
  editorInput: {
    backgroundColor: colors.raised,
    borderColor: colors.borderMuted,
    borderRadius: 9,
    borderWidth: 1,
    color: colors.text,
    fontFamily: monoFont,
    fontSize: 12,
    minHeight: 44,
    paddingHorizontal: 11,
    paddingVertical: 10,
  },
  multilineInput: { minHeight: 72, textAlignVertical: 'top' },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 9,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 16,
  },
  primaryButtonText: { color: '#052E16', fontSize: 13, fontWeight: '800' },
  resetButton: {
    alignItems: 'center',
    borderColor: colors.dangerBorder,
    borderRadius: 9,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 44,
  },
  resetText: { color: colors.danger, fontSize: 12, fontWeight: '700' },
  feedback: { color: colors.accent, fontSize: 12, marginTop: 5, textAlign: 'center' },
  otaCard: {
    backgroundColor: colors.raised,
    borderColor: colors.borderMuted,
    borderRadius: 14,
    borderWidth: 1,
    padding: 17,
  },
  otaIcon: {
    alignItems: 'center',
    backgroundColor: colors.accentSurface,
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  otaIconText: { color: colors.accent, fontSize: 27, lineHeight: 29 },
  otaTitle: { color: colors.text, fontSize: 19, fontWeight: '700', marginTop: 14 },
  otaDescription: { color: colors.secondary, fontSize: 13, lineHeight: 20, marginBottom: 16, marginTop: 7 },
  statusText: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 11, textAlign: 'center' },
  disabled: { opacity: 0.58 },
  pressed: { opacity: 0.78, transform: [{ scale: 0.97 }] },
})
